project_name: gofwd
build:
  main: .
  binary: gofwd
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - arm
  goarm:
      - 6
      - 7
  ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: mips
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
        darwin: macOS
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"
release:
  draft: true
