# goreleaser.yaml file for gofwd

builds:
  -
    id: "alpha"
    goos:
    - linux
    - freebsd
    goarch:
      - amd64
      - arm
    goarm:
      - 7
    flags:
      - -tags=netgo
    ldflags:
     - -extldflags "-static" -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: freebsd
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: 386

  -
    id: "beta"
    goos:
    - darwin
    ldflags:
      - -s -w -extldflags "-sectcreate __TEXT __info_plist Info.plist" -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: freebsd
        goarch: 386
      - goos: windows
        goarch: 386

  -
    id: "gamma"
    goos:
    - windows
    flags:
      - -tags=netgo
    ldflags:
      - -extldflags -static -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -s -w
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: freebsd
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
    hooks:
      post:
        - upx -9 "{{ .Path }}"


archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: MacOS
      linux: Linux
      freebsd: FreeBSD
      windows: Windows
      amd64: x86_64
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - duo-example.ini
      - docker_build_image.sh
      - docker_start_gofwd.sh
      - Dockerfile
      - ssl/
      
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
