on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Security Scan
        uses: securego/gosec@master
        with:
          # report triggers content trigger a failure using GH Security features
          args: '-no-fail -fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'
        id: go

      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist -p 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
